# Generated by Django 2.2.1 on 2020-02-22 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseinfo', '0002_auto_20200216_1043'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instrucor',
            new_name='Instructor',
        ),
    ]
