# Generated by Django 2.2.1 on 2020-03-26 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseinfo', '0003_auto_20200222_1147'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('section_name', 'semester', 'course')},
        ),
    ]
